export const calculatorCopy={
 lv:{title:'Aprēķiniet nomas cenu',intro:'Izvēlieties nomas veidu un ilgumu. Cena mainīsies uzreiz.',modes:['Stundas','Dienas','Nedēļas','Abonements'],duration:'Cik ilgi?',less:'Samazināt ilgumu',more:'Palielināt ilgumu',total:'Kopā par izvēlēto laiku',saving:'Ietaupījums pret 20 € stundā',book:'Izvēlēties datumu',note:'Pieejamību un rezervāciju apstiprinām sarakstē.',notes:{hours:'Piemērots ballītei, meistarklasei vai īsākai tikšanās reizei.',days:'Viena nomas diena ietver 8 stundas.',weeks:'Viena nedēļa ietver 5 darba dienas jeb 40 stundas.',months:'460 € mēnesī · 8 stundas nedēļā · vismaz 3 mēneši.'},perHour:'Vidēji stundā',perMonth:'Mēnesī',chosen:'Izvēlētais ilgums',presets:'Ātra ilguma izvēle'},
 en:{title:'Calculate your room hire',intro:'Choose a hire option and duration. Your price updates instantly.',modes:['Hours','Days','Weeks','Membership'],duration:'How long?',less:'Decrease duration',more:'Increase duration',total:'Total for your selected period',saving:'Saving compared with €20 an hour',book:'Choose a date',note:'Availability and booking are confirmed in our conversation.',notes:{hours:'For a party, workshop or a shorter gathering.',days:'One hire day includes 8 hours.',weeks:'One week includes 5 working days, or 40 hours.',months:'€460 per month · 8 hours a week · minimum 3 months.'},perHour:'Average per hour',perMonth:'Per month',chosen:'Selected duration',presets:'Quick duration selection'},
 ru:{title:'Рассчитайте стоимость аренды',intro:'Выберите вариант и срок аренды. Цена обновится сразу.',modes:['Часы','Дни','Недели','Абонемент'],duration:'На какое время?',less:'Уменьшить срок',more:'Увеличить срок',total:'Итого за выбранный срок',saving:'Экономия по сравнению с 20 € в час',book:'Выбрать дату',note:'Доступность и бронирование подтверждаем в переписке.',notes:{hours:'Для праздника, мастер-класса или короткой встречи.',days:'Один день аренды включает 8 часов.',weeks:'Одна неделя включает 5 рабочих дней или 40 часов.',months:'460 € в месяц · 8 часов в неделю · минимум 3 месяца.'},perHour:'В среднем за час',perMonth:'В месяц',chosen:'Выбранный срок',presets:'Быстрый выбор срока'}
};

export const simplePriceCopy={
 lv:{intro:'Izvēlieties ilgumu. Cena redzama uzreiz.',title:'Cik stundas būsiet kopā?',other:'Cits ilgums',total:'Kopā par telpas nomu',book:'Pārbaudīt pieejamību',note:'Pieteikšanās WhatsApp. Datumu un laiku saskaņosim sarakstē.',regular:'Vajag telpu ilgāk vai regulāri?',days:'Vairākas dienas',daysNote:'8 stundas dienā',week:'Nedēļa',weekNote:'5 darba dienas · 40 stundas',month:'Abonements',monthNote:'460 € mēnesī · 8 stundas nedēļā. Vismaz 3 mēneši, kopā no 1 380 €.',ask:'Pajautāt par nomu',included:'Viss jūsu kopā būšanai',features:['Galdi un krēsli','Virtuvīte','Bērnu rotaļu zona','Autostāvvieta pie ēkas'],terms:'Cena attiecas uz telpas nomu. Sagatavošanās un sakārtošanas laiku, īpašu aprīkojumu un pasākuma vajadzības saskaņosim iepriekš.',greeting:'Sveiki! Vēlos noskaidrot telpas pieejamību.'},
 en:{intro:'Choose your duration. See your price instantly.',title:'How many hours together?',other:'Another duration',total:'Total room hire',book:'Check availability',note:'Enquire on WhatsApp. We’ll confirm the date and time together.',regular:'Need a longer or recurring hire?',days:'Several days',daysNote:'8 hours per day',week:'One week',weekNote:'5 working days · 40 hours',month:'Membership',monthNote:'€460 per month · 8 hours per week. Minimum 3 months, from €1,380 in total.',ask:'Ask about hire',included:'Room to enjoy together',features:['Tables and chairs','Kitchenette','Children’s play area','Parking outside'],terms:'Prices cover room hire. Preparation, tidying time, special equipment and event requirements are agreed in advance.',greeting:'Hello! I would like to check room availability.'},
 ru:{intro:'Выберите время. Сразу узнайте цену.',title:'Сколько часов будете вместе?',other:'Другая длительность',total:'Итого за аренду помещения',book:'Узнать свободные даты',note:'Заявка через WhatsApp. Дату и время согласуем в переписке.',regular:'Нужна длительная или регулярная аренда?',days:'Несколько дней',daysNote:'8 часов в день',week:'Неделя',weekNote:'5 рабочих дней · 40 часов',month:'Абонемент',monthNote:'460 € в месяц · 8 часов в неделю. Минимум 3 месяца, всего от 1 380 €.',ask:'Спросить об аренде',included:'Всё для вашей встречи',features:['Столы и стулья','Мини-кухня','Детская игровая зона','Парковка у здания'],terms:'Цена включает аренду помещения. Время подготовки и уборки, специальное оборудование и пожелания к мероприятию согласуем заранее.',greeting:'Здравствуйте! Хочу узнать о доступности помещения.'}
};
