export const sideCopy={
 lv:{
  spaceTitle:'Telpa jūsu iecerēm',pricingTitle:'Telpas nomas cenas',eyebrow:'ROOM Jūrmala · Kauguri',
  description:'ROOM Jūrmala ir telpa bērnu ballītēm, ģimenes svinībām, meistarklasēm un grupu nodarbībām Skolas ielā 50. Vienā vietā iespējams ieplānot gan kopīgu maltīti, gan rotaļas vai darbošanos pie galda.',
  spaceDetails:[['Iekārtojums jūsu pasākumam','Telpā ir galdi, krēsli un brīva zona aktivitātēm. Iekārtojumu pārrunājam atbilstoši pasākuma veidam, dalībnieku skaitam un bērnu vecumam. Pirms rezervēšanas var vienoties par telpas apskati.'],['Rotaļām un kopīgam galdam','Mazākajiem pieejama rotaļu zona ar mīkstu paklāju un rotaļu elementiem. Virtuvīti var izmantot uzkodu, kūkas un dzērienu sagatavošanai un pasniegšanai. Ēdienu, dekorācijas un citus pasākuma plānus saskaņojiet iepriekš.'],['Vienai reizei vai regulāri','Izvēlieties stundas nomu īsākai tikšanās reizei vai dienas nomu ilgākam pasākumam. Pasniedzējiem un grupu vadītājiem pieejams abonements regulārām nodarbībām. Konkrētos laikus un nepieciešamo aprīkojumu saskaņojam sarakstē.']],
  planTitle:'Pirms pieteikšanās',plan:['Pastāstiet par ieceri, vēlamo datumu un sākuma laiku. Pievienojiet aptuveno dalībnieku skaitu un, ja pasākums paredzēts bērniem, viņu vecumu. Tā varēsim pārrunāt piemērotu telpas iekārtojumu.','Vienojieties arī par laiku telpas sagatavošanai un sakārtošanai. Ja nepieciešami īpaši materiāli, inventārs vai pasākuma vadītājs, pārrunājiet šīs vajadzības atsevišķi. Nomas cena attiecas uz telpu.','Pieejamību, izvēlēto nomas laiku un rezervāciju apstiprinām sarakstē. Ja vēlaties pirms lēmuma apskatīt telpu, iepriekš sazinieties ar mums.'],
  priceIntro:'Izvēlieties nomas ilgumu atbilstoši savam pasākumam. Stundas, dienas un regulārās nomas cenas ir apkopotas vienuviet, lai varētu ieplānot laiku un izmaksas.',
  rates:'Nomas iespējas',hours:'Stundas noma',packages:'Ilgākam laikam',note:'Norādīta telpas nomas maksa. Pieejamību un pasākuma vajadzības apstiprinām sarakstē.',membership:'Abonements paredzēts regulārām nodarbībām un ietver 8 stundas nedēļā. Cena ir 460 € mēnesī, minimālais termiņš ir 3 mēneši. Konkrētās dienas un laikus saskaņojam pirms nomas sākuma.',
  book:'Pieteikt datumu',allPrices:'Apskatīt visas cenas',contact:'Sazinieties ar mums',related:'Vēl par telpu',home:'Sākumlapa',location:'Skolas iela 50, Jūrmala',access:'Bezmaksas autostāvvieta pie ēkas.',faq:'Noderīgi zināt',contactNote:'Apskate un telpas noma pēc iepriekšējas vienošanās.'
 },
 en:{
  spaceTitle:'Room for your plans',pricingTitle:'Room hire prices',eyebrow:'ROOM Jūrmala · Kauguri',
  description:'ROOM Jūrmala is a venue for children’s parties, family celebrations, workshops and group classes at Skolas iela 50. Plan a shared meal, games or activities around the table in one space.',
  spaceDetails:[['A layout for your event','The room has tables, chairs and an open activity area. We discuss the arrangement around your event, group size and children’s ages. You can arrange a viewing before booking.'],['Play and a shared table','Younger guests have a play area with a soft carpet and play equipment. Use the kitchenette to prepare and serve snacks, cake and drinks. Discuss food, decorations and your event plans in advance.'],['One occasion or regular sessions','Choose hourly hire for a short gathering or a day for a longer event. Instructors and group leaders can arrange recurring hire through a membership. We agree on specific times and equipment needs in our conversation.']],
  planTitle:'Before you book',plan:['Tell us about your plans, preferred date and start time. Include an approximate group size and, for children’s events, their ages so we can discuss a suitable layout.','Allow time for preparing and tidying the room. Discuss any special materials, equipment or an event host separately. Hire prices cover the space.','Availability, your hire period and the booking are confirmed in our conversation. Contact us in advance if you would like to see the room before deciding.'],
  priceIntro:'Choose a hire period to suit your event. Hourly, daily and recurring options are listed together so you can plan your time and budget.',
  rates:'Hire options',hours:'Hourly hire',packages:'For longer stays',note:'Prices cover room hire. Availability and event requirements are confirmed in our conversation.',membership:'Membership is for recurring classes and includes 8 hours a week. It costs €460 per month, with a minimum term of 3 months. We agree on the days and times before the hire begins.',
  book:'Request a date',allPrices:'View all prices',contact:'Get in touch',related:'Explore the space',home:'Home',location:'Skolas iela 50, Jūrmala',access:'Free parking outside the building.',faq:'Useful to know',contactNote:'Viewings and room hire by prior arrangement.'
 },
 ru:{
  spaceTitle:'Место для ваших планов',pricingTitle:'Стоимость аренды',eyebrow:'ROOM Jūrmala · Каугури',
  description:'ROOM Jūrmala предлагает помещение для детских праздников, семейных встреч, мастер-классов и групповых занятий на Skolas iela 50. Здесь можно устроить общий стол, игры и творческие занятия.',
  spaceDetails:[['Расстановка для вашего события','В помещении есть столы, стулья и свободная зона для занятий. Расстановку обсудим с учётом формата встречи, числа участников и возраста детей. До бронирования можно договориться об осмотре.'],['Игры и общий стол','Для малышей есть игровая зона с мягким ковром и игровыми элементами. Мини-кухня подойдёт для подготовки и подачи закусок, торта и напитков. Еду, украшения и план праздника согласуйте заранее.'],['Разовые и регулярные встречи','Для короткой встречи подойдёт почасовая аренда, для более длительного события можно арендовать помещение на день. Преподавателям и ведущим групп доступен абонемент. Время и необходимое оборудование согласуем в переписке.']],
  planTitle:'Перед бронированием',plan:['Расскажите о ваших планах, желаемой дате и времени начала. Укажите примерное число участников и возраст детей, если событие предназначено для них. Это поможет обсудить удобную расстановку.','Предусмотрите время для подготовки и уборки помещения. Материалы, специальное оборудование или ведущего мероприятия обсудите отдельно. Указанные цены относятся к аренде помещения.','Доступность, срок аренды и бронирование подтверждаем в переписке. Если хотите сначала осмотреть помещение, свяжитесь с нами заранее.'],
  priceIntro:'Выберите срок аренды под ваше мероприятие. Почасовые, дневные и регулярные варианты собраны на одной странице, чтобы было удобно спланировать время и расходы.',
  rates:'Варианты аренды',hours:'Почасовая аренда',packages:'На более долгий срок',note:'Указана стоимость аренды помещения. Доступность и пожелания к мероприятию подтверждаем в переписке.',membership:'Абонемент рассчитан на регулярные занятия и включает 8 часов в неделю. Стоимость 460 € в месяц, минимальный срок 3 месяца. Дни и время согласуем до начала аренды.',
  book:'Выбрать дату',allPrices:'Все цены',contact:'Свяжитесь с нами',related:'Подробнее о помещении',home:'Главная',location:'Skolas iela 50, Юрмала',access:'Бесплатная парковка у здания.',faq:'Полезно знать',contactNote:'Осмотр и аренда по предварительной договорённости.'
 }
};
