export const sideCopy={
 lv:{
  spaceTitle:'Vieta jūsu svētkiem un nodarbībām',pricingTitle:'Telpas nomas cenas',eyebrow:'ROOM Jūrmala · Kauguri',
  description:'Pie mums Kauguros var nosvinēt dzimšanas dienu, satikt ģimeni un draugus vai vadīt nodarbību. Telpā ir vieta gan kopīgam galdam, gan bērnu rotaļām un kustībai.',
  spaceDetails:[['Iekārtosim telpu jūsu pasākumam','Galdi un krēsli jau ir uz vietas. Pastāstiet, ko plānojat un cik cilvēku būs, lai varam vienoties par ērtu iekārtojumu. Ja vēlaties vispirms apskatīt telpu, uzrakstiet mums.'],['Kamēr bērni rotaļājas','Bērniem ir rotaļu stūrītis ar mīkstu paklāju un rotaļlietām, bet pieaugušie var apsēsties un aprunāties. Virtuvītē var sagatavot uzkodas, salikt cienastu un pasniegt kūku. Par ēdienu un dekorācijām vienosimies pirms pasākuma.'],['Uz dažām stundām vai regulāri','Telpu var iznomāt uz dažām stundām vai visu dienu. Ja vadāt nodarbības un meklējat pastāvīgu vietu savai grupai, piedāvājam arī abonementu. Uzrakstiet, kurās dienās un laikos vēlaties nākt.']],
  planTitle:'Kā rezervēt telpu',plan:['Uzrakstiet mums WhatsApp, ko vēlaties rīkot, kurā datumā un cikos. Norādiet aptuveno viesu skaitu un bērnu vecumu, ja plānojat bērnu ballīti.','Vienosimies arī par laiku, kas vajadzīgs dekorēšanai un sakārtošanai. Cenā ir iekļauta telpas noma. Ja nepieciešams pasākuma vadītājs, materiāli vai papildu aprīkojums, pārrunāsim to atsevišķi.','Atbildēsim, vai izvēlētais laiks ir brīvs, un apstiprināsim rezervāciju sarakstē.'],
  priceIntro:'Izvēlieties nomas ilgumu atbilstoši savam pasākumam. Stundas, dienas un regulārās nomas cenas ir apkopotas vienuviet, lai varētu ieplānot laiku un izmaksas.',
  rates:'Nomas iespējas',hours:'Stundas noma',packages:'Ilgākam laikam',note:'Cena par telpas nomu. Par brīvajiem laikiem jautājiet mums WhatsApp.',membership:'Abonements paredzēts regulārām nodarbībām un ietver 8 stundas nedēļā. Cena ir 460 € mēnesī, minimālais termiņš ir 3 mēneši. Konkrētās dienas un laikus saskaņojam pirms nomas sākuma.',
  book:'Izvēlēties datumu',allPrices:'Apskatīt visas cenas',contact:'Sazinieties ar mums',related:'Vēl par telpu',home:'Sākumlapa',location:'Skolas iela 50, Jūrmala',access:'Bezmaksas autostāvvieta pie ēkas.',faq:'Noderīgi zināt',contactNote:'Lai apskatītu telpu, iepriekš sarunāsim laiku.'
 },
 en:{
  spaceTitle:'Room for your plans',pricingTitle:'Room hire prices',eyebrow:'ROOM Jūrmala · Kauguri',
  description:'ROOM Jūrmala is a venue for children’s parties, family celebrations, workshops and group classes at Skolas iela 50. Plan a shared meal, games or activities around the table in one space.',
  spaceDetails:[['A layout for your event','The room has tables, chairs and an open activity area. We discuss the arrangement around your event, group size and children’s ages. You can arrange a viewing before booking.'],['Play and a shared table','Younger guests have a play area with a soft carpet and play equipment. Use the kitchenette to prepare and serve snacks, cake and drinks. Discuss food, decorations and your event plans in advance.'],['One occasion or regular sessions','Choose hourly hire for a short gathering or a day for a longer event. Instructors and group leaders can arrange recurring hire through a membership. We agree on specific times and equipment needs in our conversation.']],
  planTitle:'Before you book',plan:['Tell us about your plans, preferred date and start time. Include an approximate group size and, for children’s events, their ages so we can discuss a suitable layout.','Allow time for preparing and tidying the room. Discuss any special materials, equipment or an event host separately. Hire prices cover the space.','Availability, your hire period and the booking are confirmed in our conversation. Contact us in advance if you would like to see the room before deciding.'],
  priceIntro:'Choose a hire period to suit your event. Hourly, daily and recurring options are listed together so you can plan your time and budget.',
  rates:'Hire options',hours:'Hourly hire',packages:'For longer stays',note:'Prices cover room hire. Availability and event requirements are confirmed in our conversation.',membership:'Membership is for recurring classes and includes 8 hours a week. It costs €460 per month, with a minimum term of 3 months. We agree on the days and times before the hire begins.',
  book:'Request a date',allPrices:'View all prices',contact:'Get in touch',related:'Explore the space',home:'Home',location:'Skolas iela 50, Jūrmala',access:'Free parking outside the building.',faq:'Useful to know',contactNote:'Viewings and room hire by prior arrangement.'
 },
 ru:{
  spaceTitle:'Место для ваших планов',pricingTitle:'Стоимость аренды',eyebrow:'ROOM Jūrmala · Каугури',
  description:'ROOM Jūrmala предлагает помещение для детских праздников, семейных встреч, мастер-классов и групповых занятий на Skolas iela 50. Здесь можно устроить общий стол, игры и творческие занятия.',
  spaceDetails:[['Расстановка для вашего события','В помещении есть столы, стулья и свободная зона для занятий. Расстановку обсудим с учётом формата встречи, числа участников и возраста детей. До бронирования можно договориться об осмотре.'],['Игры и общий стол','Для малышей есть игровая зона с мягким ковром и игровыми элементами. Мини-кухня подойдёт для подготовки и подачи закусок, торта и напитков. Еду, украшения и план праздника согласуйте заранее.'],['Разовые и регулярные встречи','Для короткой встречи подойдёт почасовая аренда, для более длительного события можно арендовать помещение на день. Преподавателям и ведущим групп доступен абонемент. Время и необходимое оборудование согласуем в переписке.']],
  planTitle:'Перед бронированием',plan:['Расскажите о ваших планах, желаемой дате и времени начала. Укажите примерное число участников и возраст детей, если событие предназначено для них. Это поможет обсудить удобную расстановку.','Предусмотрите время для подготовки и уборки помещения. Материалы, специальное оборудование или ведущего мероприятия обсудите отдельно. Указанные цены относятся к аренде помещения.','Доступность, срок аренды и бронирование подтверждаем в переписке. Если хотите сначала осмотреть помещение, свяжитесь с нами заранее.'],
  priceIntro:'Выберите срок аренды под ваше мероприятие. Почасовые, дневные и регулярные варианты собраны на одной странице, чтобы было удобно спланировать время и расходы.',
  rates:'Варианты аренды',hours:'Почасовая аренда',packages:'На более долгий срок',note:'Указана стоимость аренды помещения. Доступность и пожелания к мероприятию подтверждаем в переписке.',membership:'Абонемент рассчитан на регулярные занятия и включает 8 часов в неделю. Стоимость 460 € в месяц, минимальный срок 3 месяца. Дни и время согласуем до начала аренды.',
  book:'Выбрать дату',allPrices:'Все цены',contact:'Свяжитесь с нами',related:'Подробнее о помещении',home:'Главная',location:'Skolas iela 50, Юрмала',access:'Бесплатная парковка у здания.',faq:'Полезно знать',contactNote:'Осмотр и аренда по предварительной договорённости.'
 }
};
